spring:
  jackson:
    defaultPropertyInclusion: NON_NULL

server:    
  http:
    encoding:
      enabled: true
      force: true
      charset: UTF-8
  port: 8080

logging.level:
  org.pplm.plusy: debug

plusy:
  store:
    limit: 100
    path: 
      data: E:/work/plusy/data
      readstatus:  E:/work/plusy/readstatus
  config: 
    spider: E:/work/plusy/spider.json
    user: E:/work/plusy/user.json
  scrapyd:
    project: plusy
    url: http://47.95.213.130:8888
  threadpool.size: 20
  auth: false
  
  